baseurl: "/"

permalink: pretty

collections:
  team:
    output: true
# timezone: Europe/Amsterdam

# kramdown:
#   input: Kramdown
plugins:
  - jekyll-compress-images

compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

imageoptim:
  pngout: false
  svgo: false
  verbose: false
  oxypng: false
  pngcrush: false
