# backend:
#   name: github
#   repo: DaanBoertien/First-Jekkyl-website

backend:
  name: git-gateway
  branch: main

# backend:
#   name: git-gateway
#   branch: master

media_folder: assets/img/uploads/

collections:
  - name: "team_members"
    label: "Teamleden"
    label_singular: "Teamlid"
    folder: "_team_members/"
    create: true
    summary: "{{name}}"
    slug: "{{name}}"
    editor:
      preview: false
    fields:
      - { label: "Naam", name: "name", widget: "string" }
      - { label: "Emailadres", name: "email", widget: "string" }
      - { label: "Telefoonnummer", name: "phonenumber", widget: "string" }
      - { label: "Foto", name: "photo_url", widget: "image" }
      - {
          label: "Omschrijving foto",
          name: "photo_description",
          widget: "string",
        }
