# backend:
#   name: github
#   repo: DaanBoertien/First-Jekkyl-website

backend:
  name: git-gateway
  branch: master
# backend:
#   name: git-gateway
#   branch: master

media_folder: assets/images/upload/

collections:
  - name: "team"
    label: "Teamleden"
    label_singular: "Teamlid"
    folder: "_team/"
    create: true
    summary: "{{title}}"
    slug: "{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "teammembers",
        }
      - { label: "Naam", name: "title", widget: "string" }
      - { label: "Functie", name: "function", widget: "string" }
      - { label: "Emailadres", name: "email", widget: "string" }
      - { label: "Telefoonnummer", name: "phonenumber", widget: "string" }
      - { label: "Foto", name: "photo_url", widget: "image" }
      - {
          label: "Omschrijving foto",
          name: "photo_description",
          widget: "string",
        }
      - { label: "Omschrijving", name: "summary", widget: "markdown" }
      - label: "Achtergrondkleur"
        name: "bg_color"
        widget: "select"
        options: ["Donkerblauw", "Lichtblauw", "Groen", "Grijs", "Geel", "Rood"]
  - name: "content"
    label: "Teksten"
    files:
      - name: "home"
        label: "Home"
        file: "_data/home.yml"
        editor:
          preview: false
        fields:
          - label: "Landing Slogan"
            name: "slogan"
            widget: "string"
          - label: "Landing Tekst"
            name: "landing-tekt"
            widget: "markdown"
          - label: "Missie titel"
            name: "waar-wij-voor-staan"
            widget: "string"
          - label: "Missie tekst"
            name: "waar-wijvoor-staan-tekst"
            widget: "markdown"
          - label: "Waarde 1 titel"
            name: "waarde-1-titel"
            widget: "string"
          - label: "Waarde 1 tekst"
            name: "waarde-1-tekst"
            widget: "markdown"
          - label: "Waarde 1 afbeelding"
            name: "waarde-1-afbeelding"
            widget: "image"
          - label: "Waarde 2 titel"
            name: "waarde-2-titel"
            widget: "string"
          - label: "Waarde 2 tekst"
            name: "waarde-2-tekst"
            widget: "markdown"
          - label: "Waarde 2 afbeelding"
            name: "waarde-2-afbeelding"
            widget: "image"
          - label: "Waarde 3 titel"
            name: "waarde-3-titel"
            widget: "string"
          - label: "Waarde 3 tekst"
            name: "waarde-3-tekst"
            widget: "markdown"
          - label: "Waarde 3 afbeelding"
            name: "waarde-3-afbeelding"
            widget: "image"

          - label: "Wat wij doen"
            name: "wat-wij-doen"
            widget: "string"
          - label: "Wat wij doen uitleg"
            name: "wat-wij-doen-tekst"
            widget: "markdown"

          - label: "Wat wij doen 1"
            name: "wat-wij-doen-1-titel"
            widget: "string"
          - label: "Wat wij doen 1 tekst"
            name: "wat-wij-doen-1-tekst"
            widget: "markdown"
          - label: "Wat wij doen 1 contact"
            name: "wat-wij-doen-1-contact"
            widget: "markdown"
          - label: "Wat wij doen 1 button"
            name: "wat-wij-doen-1-button"
            widget: "string"

          - label: "Wat wij doen 2"
            name: "wat-wij-doen-2-titel"
            widget: "string"
          - label: "Wat wij doen 2 tekst"
            name: "wat-wij-doen-2-tekst"
            widget: "markdown"
          - label: "Wat wij doen 2 contact"
            name: "wat-wij-doen-2-contact"
            widget: "markdown"
          - label: "Wat wij doen 2 button"
            name: "wat-wij-doen-2-button"
            widget: "string"
          - label: "Wat wij doen 3"
            name: "wat-wij-doen-3-titel"
            widget: "string"
          - label: "Wat wij doen 3 tekst"
            name: "wat-wij-doen-3-tekst"
            widget: "markdown"
          - label: "Wat wij doen 3 contact"
            name: "wat-wij-doen-3-contact"
            widget: "markdown"
          - label: "Wat wij doen 3 button"
            name: "wat-wij-doen-3-button"
            widget: "string"
          - label: "Hoe wij werken button"
            name: "hoe-wij-werken"
            widget: "string"

          - label: "Wie wij zijn titel"
            name: "wie-wij-zijn"
            widget: "string"

          - label: "Actievraag"
            name: "actievraag"
            widget: "string"
          - label: "Actievraag omschrijving"
            name: "actievraag-subtitel"
            widget: "string"
          - label: "Actievraag Button"
            name: "actievraag-button"
            widget: "string"

          - label: "Partners Titel"
            name: "partners-titel"
            widget: "string"
          - label: "Logo's Bedrijven"
            name: "logos"
            widget: "list"
            fields:
              - label: "Naam Bedrijf"
                name: "naam-bedrijf"
                widget: "string"
              - label: "Logo Bedrijf"
                name: "logo-bedrijf"
                widget: "image"

          - label: "Contact Titel"
            name: "contact-titel"
            widget: "string"
          - label: "Contact Omschrijving"
            name: "contact-omschrijving"
            widget: "markdown"
          - label: "Label Contactformulier Naam"
            name: "contact-naam"
            widget: "string"
          - label: "Label Contactformulier E-mail"
            name: "contact-email"
            widget: "string"
          - label: "Label Contactformulier Onderwerp"
            name: "contact-onderwerp"
            widget: "string"
          - label: "Label Contactformulier Bericht"
            name: "contact-bericht"
            widget: "string"
          - label: "Contactformulier Button"
            name: "contact-button"
            widget: "string"

          - label: "Uitnodiging"
            name: "uitnodiging"
            widget: "string"
          - label: "Adres"
            name: "adres"
            widget: "string"
          - label: "Postcode"
            name: "postcode"
            widget: "string"
          - label: "Afbeelding Kantoor"
            name: "afbeelding-kantoor"
            widget: "image"
